SUSHI_VERSION = 1.1.0

# prefix _must_ be an absolute path.
prefix    = $(HOME)
bindir    = $(prefix)/bin
sharedir  = $(prefix)/share
docdir    = $(sharedir)/doc
localedir = $(sharedir)/locale
mandir    = $(sharedir)/man

CHMOD      = chmod
GREP       = grep
GZIP       = gzip
INSTALL    = install
LN         = ln
PKG_CONFIG = pkg-config
RM         = rm
SED        = sed
SORT       = sort

ifndef VERBOSE
	QUIET_GEN = @echo "[GEN]  $@";
else
	QUIET_GEN =
endif
